### ISSUE TITLE
Android Null Pointer Exception when calling Communities.getActivities()

### ISSUE THREAD

**Issue by mesrob-crew** [getsocial-im/getsocial-flutter-sdk#1]
Started getting the following error when calling getActivities. The code works in iOS build but fails for Android with the following stack trace below. I'm able to create and get a group on Android, just fails on getActivities.

1. Code invoked from Flutter SDK
```
ActivitiesQuery query = ActivitiesQuery.inGroup("groupid");
final paging = PagingQuery(query);
final activities = await Communities.getActivities(paging);
```

2. Received stack trace
```
[  +33 ms] E/AndroidRuntime(15027): FATAL EXCEPTION: pool-38-thread-1
[        ] E/AndroidRuntime(15027): Process: app.themarvin.dev, PID: 15027
[        ] E/AndroidRuntime(15027): java.lang.NullPointerException: Attempt to invoke virtual method 'int im.getsocial.sdk.communities.PollStatus.getValue()' on a null object reference
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.jjbQypPegg.retention(CommunitiesAccessHelper.java:114)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.a.b.jjbQypPegg.getsocial(CommunitiesThriftConverter.java:4787)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.internal.c.JbBdMtJmlU.dau(ThriftyCommunicationLayer.java:619)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.a.c.KSZKMmRWhZ.getsocial(GetActivitiesUseCase.java:17)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.a.c.QhisXzMgay.attribution(PagingUseCase.java:13)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.a.c.QhisXzMgay.lambda$kbOec_0FqkXKg7_w_NU-G8mXdwE(Unknown Source:0)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.communities.a.c.-$$Lambda$QhisXzMgay$kbOec_0FqkXKg7_w_NU-G8mXdwE.call(Unknown Source:4)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.internal.c.k.jjbQypPegg.attribution(AsyncUseCase.java:93)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.internal.c.k.jjbQypPegg.lambda$UeUicyGFtcGsOtaOtedxttI4G_g(Unknown Source:0)
[        ] E/AndroidRuntime(15027): 	at im.getsocial.sdk.internal.c.k.-$$Lambda$jjbQypPegg$UeUicyGFtcGsOtaOtedxttI4G_g.run(Unknown Source:8)
[        ] E/AndroidRuntime(15027): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(15027): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(15027): 	at java.lang.Thread.run(Thread.java:919)
```

Debug Info:
Printed out method and body being passed to the method channel to Android.
method: `Communities.getActivities`
body: `{\"query\":{\"ids\":{\"ids\":[\"ddd59aad-e11a-4bc7-b064-35e910213a05\"],\"type\":3},\"author\":null,\"tag\":null},\"limit\":25,\"next\":\"\"}`

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/mesrob/Library/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/mesrob/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

**Comment by gaborvass** [comment]
Hi,
The issue happens only if you manually update the dependencies in build.gradle file to use version 7.5.0 of getsocial-core library. We released polls feature only for native Android and iOS, other SDKs, like Flutter don't support polls yet. Please change back the dependencies to the original value, 7.4.8.

**Comment by gaborvass** [comment]
Hi,
Please add "version" property to your app's `build.gradle` file, like:
`
﻿getsocial {
﻿ appId [YOUR APP ID]
﻿ version "7.4.11"
﻿}
`

﻿it will fix the issue, meanwhile we'll release a fixed Android SDK version.

**Comment by mesrob-crew** [comment]
> Hi,
> Please add "version" property to your app's `build.gradle` file, like:
> `﻿getsocial { ﻿ appId [YOUR APP ID] ﻿ version "7.4.11" ﻿}`
> 
> ﻿it will fix the issue, meanwhile we'll release a fixed Android SDK version.

Perfect, adding the version field fixed it. Thanks for the quick response @gaborvass, appreciate it!
