### ISSUE TITLE
SDK does not auto register device for Push Notifications

### ISSUE THREAD

**Issue by mesrob-crew** [getsocial-im/getsocial-flutter-sdk#2]
I am trying to setup push notifications for Android but the SDK is not able to register the device successfully. I've set up the Android Notification Settings with my Firebase Cloud Messaging Server ID and Key. Please note I already have notifications working on my app outside of GetSocial. I've tried on both simulator and physical device.

With `autoRegister` flag to true I get the following error: 
```
[ +344 ms] D/GetSocial_upgqDBbsrL( 8781): GetSocial DeviceId: 375e8eac-5dc7-48d9-91fe-2b868fea0bc7
[+7038 ms] W/GetSocial_XdbacJlTDQ( 8781): Failed to obtain push token
```

When I switch the configuration `autoRegister` to false and call `registerDevice()` manually I get:
```
[  +56 ms] I/flutter (17421): Notifications.registerDevice
[        ] I/flutter (17421): 
[   +6 ms] W/GetSocial_JSON(17421): Call failed: Notifications.registerDevice, body: 
[   +1 ms] W/GetSocial_JSON(17421): Unsupported method: Notifications.registerDevice, body: 
[        ] W/GetSocial_JSON(17421): java.lang.RuntimeException: Unsupported method: Notifications.registerDevice, body: 
[        ] W/GetSocial_JSON(17421): 	at im.getsocial.sdk.json.GetSocialJson.callAsync(GetSocialJson.java:1553)
[        ] W/GetSocial_JSON(17421): 	at im.getsocial.GetSocialPlugin.onMethodCall(GetSocialPlugin.java:67)
[        ] W/GetSocial_JSON(17421): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] W/GetSocial_JSON(17421): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] W/GetSocial_JSON(17421): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] W/GetSocial_JSON(17421): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/GetSocial_JSON(17421): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] W/GetSocial_JSON(17421): 	at android.os.Looper.loop(Looper.java:183)
[        ] W/GetSocial_JSON(17421): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
[        ] W/GetSocial_JSON(17421): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/GetSocial_JSON(17421): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] W/GetSocial_JSON(17421): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Using version 7.4.11 due to: https://github.com/getsocial-im/getsocial-flutter-sdk/issues/1
```
getsocial {
    appId "xyz" // Dev App Id
    version "7.4.11"
}
```

GetSocial Android Configuration: `getsocial.json`
```
{
    "autoInit": true,
    "pushNotifications": {
        "android": {
            "titleColor": null,
            "messageColor": null,
            "channelName": null,
            "icon": null,
            "backgroundImage": null,
            "channelDescription": null,
            "largeIcon": null
        },
        "autoRegister": true,
        "customListener": true,
        "foreground": false
    },
    "disableFacebookReferralCheck": false,
    "uiConfig": null
}
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/mesrob/Library/flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/mesrob/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Pixel 3 (mobile)   • 8C7X1K15P                            • android-arm64  • Android 11 (API 30)
    • iPhone 11 (mobile) • B7184D89-6AC3-4FE6-B5B2-39107ACC6284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

**Comment by gaborvass** [comment]
Hi,
Please update GetSocial plugin version to 7.5.1, it fixes the issue with `Notifications.register` method.
To understand the other issue you reported, please share the complete ADB logs of your app session.

**Comment by mesrob-crew** [comment]
Hi @gaborvass, updating to Flutter plugin version 7.5.1 resolved the `register()` issue. I have removed specifying the version field in the `android/app/build.gradle` file as well.

Still seeing the error `Failed to obtain push token`. ADB Log attached.
[adb_log.txt](https://github.com/getsocial-im/getsocial-flutter-sdk/files/6870168/adb_log.txt)

**Comment by gaborvass** [comment]
Thanks for the logs!
Looks like you're using Flutter-FirebaseCloudMessaging package and it causes some issue in our plugin.
If you want to use only GetSocial Push Notifications, I would suggest removing Flutter-FCM. 
If that's not possible, we'll investigate what is the issue if both plugins are added.

**Comment by mesrob-crew** [comment]
I see, thanks for the update. I have my own notification systems for other parts of my app so definitely I'll still need FCM. If you can please find a way to make both work, great appreciate it. Let me know if I can be of help!

**Comment by gaborvass** [comment]
Found the solution: please add the following dependency to your app's `build.gradle` file:
`implementation("com.google.firebase:firebase-iid")`

**Comment by mesrob-crew** [comment]
That fixed it! Thanks for addressing the issue. Will let you know if anything comes up.
